### PR TITLE
Upgrade ruby and jekyll dependencies

### PR DESCRIPTION
**Pull request by henri-tremblay**
Having a Gemfile allows to use Ruby easily without rvm. You can then use rbenv if needed as  environment manager. A gemset can be used if wanted. The gemset can also be created locally to easily delete it if needed.

Html-proofer is a nice html validator. It checks images, links and format.

### CODE REVIEW

**Comment by akomakom** [comment]
From cursory googling, there is no rbenv for Windows.  @ljacomet, what would you like me to test?  bundle install?

**Comment by henri-tremblay** [comment]
I can test it on Windows. Or to rephrase, I can write a procedure for Windows. When I have 2 minutes. About Jenkins, we can also look at that. I suggest to leave it on the ice for now and we take care of it together in a couple of weeks.

**Comment by akomakom** [comment]
On second thought, there is nothing in this PR that would break the existing process, so never mind :) ... but  if rbenv has some advantages, I'm happy to switch.

**Comment by ljacomet** [comment]
@akomakom The delete of `default.gems` would cause the RVM based build to break. That's what's used to install the required gems.

**Comment by akomakom** [comment]
@ljacomet, I missed that deletion.  Perhaps we can split that bit to a separate PR for later so I can take my time in changing the process.

**Comment by henri-tremblay** [comment]
Yes we could. And rvm should be able to support Gemfiles. It would mean a tiny change in the process. I can put it back for now and revisit when I have time.

**Comment by akomakom** [comment]
@henri-tremblay you're quite right, in other rvm-backed projects I'm using Gemfile with bundle install, not default.gems.  Shouldn't be a big deal either way.

**Comment by akomakom** [comment]
I'm finally implementing some semi-cohesive build (test?) automation for this on azure, I'll be closing/opening this, sorry for the noise (it's the only "test this please" we've figured out for azure), and I need this PR because it has a Gemfile.

**Comment by akomakom** [comment]
So... what I tried to do was automatically build the site and host a **staging** copy for inspection.

### Good news: 
- I can have Azure Devops build the site with jekyll without too much trouble.  It's not 100% done but it works.
- I can even have Azure commit the results... but not for PR builds (PR builds have no GitHub OAuth tokens in Azure).  So no staging PR builds.  It can commit builds from master for [inspection here](http://www.ehcache.org/ehcache.org-site/), I'm using the web-hosted "gh-pages" branch in this repo.

### Bad news:
- Since I can't commit the results for PR builds, I need to host them somewhere else or gain github commit access by some other means... which is not a technical problem, but rather a security problem.  Thoughts welcome.

**Comment by akomakom** [comment]
Never mind, I think I found a secure solution, stand by.

**Comment by akomakom** [comment]
Good news:  site gets partially built and pushed to github (latest build overwrites previous). 
Bad news: site uses absolute links and cannot be hosted in a subfolder.
Bad news: github hosting only allows one top-level site per org (ehcache.github.io ---> www.ehcache.org).  Any other sites have to live in www.ehcache.org/repo-name ( www.ehcache.org/ehcache.org-site/ in this case)

@henri-tremblay @anthonydahanne 
Ideas?  Can we host this elsewhere?  Can we fix the links?  Do we need the links to be right?

**Pull request merged**
