### PR TITLE
Issue #35 (talk section) and improvements

### PR DESCRIPTION
**Pull request by mathieucarbou**
- added talk section with some talsk and links
- release notes on menu item points to the release note section
- Excluded idea config folder

### CODE REVIEW

**Comment by mathieucarbou** [comment]
rebased on master just now.

**Comment by mathieucarbou** [comment]
Fixes issue #27.

**Comment by mathieucarbou** [comment]
@ljacomet @jhouserizer : FYI.

**Comment by mathieucarbou** [comment]
@ljacomet : rebased!

**Comment by ljacomet** [comment]
Let's talk about this - because there is already such content in the [recent events section](http://www.ehcache.org/events/)

**Comment by mathieucarbou** [comment]
Replaced by #49

**Pull request closed without merging**
